direction: right

client -> go http server: request

go http server -> middleware handler -> mux -> handler function

handler function -> mux : response

mux -> middleware handler -> go http server -> client
